modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT" #mandatory
issueTrackerURL="https://github.com/Wallace-Watler/jiggly-slimes/issues" #optional

[[mods]] #mandatory
modId="jigglyslimes" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Jiggly Slimes" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Wallace-Watler/jiggly-slimes/updateJSON/updates.json" #optional
displayURL="https://github.com/Wallace-Watler/jiggly-slimes" #optional
#logoFile="" #optional
#credits="" #optional
authors="WallaceTheWizard" #optional
description='''A client-side mod that gives slimes a jiggly appearance.''' #mandatory

[[dependencies.jigglyslimes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.jigglyslimes]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="CLIENT"
